#include "repository/JsonSampleRepository.h"

#include "gmock/gmock.h"

#include <cstdio>
#include <string>

using namespace testing;

class JsonSampleRepositoryTest : public Test
{
    protected:
        void SetUp() override
        {
            std::remove(file_path.c_str());
        }

        void TearDown() override
        {
            std::remove(file_path.c_str());
        }

        std::string file_path = "test_samples.json";
};

TEST_F(JsonSampleRepositoryTest, FindAllReturnsEmptyWhenFileDoesNotExist)
{
    JsonSampleRepository repository(file_path);

    EXPECT_TRUE(repository.findAll().empty());
}

TEST_F(JsonSampleRepositoryTest, SaveAssignsAutoGeneratedId)
{
    JsonSampleRepository repository(file_path);

    const Sample saved = repository.save(Sample{ "", "실리콘 웨이퍼-8인치", 500, 0.92 });

    EXPECT_EQ(saved.id, "S-001");
}

TEST_F(JsonSampleRepositoryTest, SecondSaveContinuesSequence)
{
    JsonSampleRepository repository(file_path);
    repository.save(Sample{ "", "실리콘 웨이퍼-8인치", 500, 0.92 });

    const Sample second = repository.save(Sample{ "", "GaN 에피택셜-4인치", 300, 0.78 });

    EXPECT_EQ(second.id, "S-002");
}

TEST_F(JsonSampleRepositoryTest, DataSurvivesRepositoryRecreation)
{
    {
        JsonSampleRepository repository(file_path);
        repository.save(Sample{ "", "실리콘 웨이퍼-8인치", 500, 0.92 });
    }

    JsonSampleRepository reloaded(file_path);
    ASSERT_EQ(reloaded.findAll().size(), 1u);
    EXPECT_EQ(reloaded.findAll()[0].name, "실리콘 웨이퍼-8인치");
}

TEST_F(JsonSampleRepositoryTest, SequenceContinuesAfterRecreation)
{
    {
        JsonSampleRepository repository(file_path);
        repository.save(Sample{ "", "A", 1, 1.0 });
    }

    JsonSampleRepository reloaded(file_path);
    const Sample second = reloaded.save(Sample{ "", "B", 1, 1.0 });

    EXPECT_EQ(second.id, "S-002");
}

TEST_F(JsonSampleRepositoryTest, FindByIdReturnsNulloptWhenMissing)
{
    JsonSampleRepository repository(file_path);

    EXPECT_FALSE(repository.findById("S-999").has_value());
}

TEST_F(JsonSampleRepositoryTest, UpdateExistingSampleOverwritesFields)
{
    JsonSampleRepository repository(file_path);
    const Sample saved = repository.save(Sample{ "", "Original", 100, 0.5 });

    repository.save(Sample{ saved.id, "Updated", 200, 0.9 });

    const std::optional<Sample> found = repository.findById(saved.id);
    ASSERT_TRUE(found.has_value());
    EXPECT_EQ(found->name, "Updated");
    EXPECT_EQ(found->avg_production_time_ms, 200);
}

TEST_F(JsonSampleRepositoryTest, NewSampleStartsWithZeroStock)
{
    JsonSampleRepository repository(file_path);

    const Sample saved = repository.save(Sample{ "", "실리콘 웨이퍼-8인치", 500, 0.92 });

    EXPECT_EQ(saved.physical_stock, 0);
    EXPECT_EQ(saved.available_stock, 0);
}

TEST_F(JsonSampleRepositoryTest, StockFieldsSurviveRepositoryRecreation)
{
    {
        JsonSampleRepository repository(file_path);
        const Sample saved = repository.save(Sample{ "", "실리콘 웨이퍼-8인치", 500, 0.92 });

        Sample updated = saved;
        updated.physical_stock = 480;
        updated.available_stock = 330;
        repository.save(updated);
    }

    JsonSampleRepository reloaded(file_path);
    ASSERT_EQ(reloaded.findAll().size(), 1u);
    EXPECT_EQ(reloaded.findAll()[0].physical_stock, 480);
    EXPECT_EQ(reloaded.findAll()[0].available_stock, 330);
}
